export const translationsEn =
{
    HeaderTitle: "Our Heart Together With Earthquake Areas",
    Help: "Help",
    RequestsList: "Requests List",
    Homepage: "Homepage",
    CreateRequest: "Create Request",
    ProvidedRequestsByMe: "Provided Requests By Me",
    ProvidedRequest: "Provided Request",
    TotalRequest: "Total Request",
    WaitingRequest: "Waiting Request",
    Name: "Name",
    EmployeeNo: "Employee No",
    GSM: "GSM",
    Email: "Email",
    ExpectedDeliveryDate: "Expected Delivery Date",
    Adress: "Adress",
    Quantity: "Quantity",
    Price: "Price",
    PriceUnit: "Price Unit",
    MeasureUnit: "Measure Unit",
    PurchaseType: "Purchase Type",
    ProvidingType: "Providing Type",
    DeliveryType: "Delivery Type",
    Url: "URL",
    RequesterUppercase: "REQUESTER",
    ProductUppercase: "PRODUCT",
    SpecialProduct: "Special Product",
    AddProduct: "Add Product",
    PleaseFill: "Please fill.",

    ProductName: "Product Name",
    ProductSector: "Product Sector",
    ProductQuantity: "Product Quantity",
    ProductPrice: "Product Price",
    ProviderCompany: "Provider Company",
}