export const translationsEn =
{
    HeaderTitle: "Our Hearts and Supports are in the Earthquake Zone",
    HeaderDescription: "From the first moment of the great natural disaster that our country has experienced, our hearts beat with our friends and relatives who were affected by the disaster.<br><br>Through our one Heart Solidarity Platform, you can help our loved ones to rebuild their lives and support their needs.    <br><br>You can share all your questions, suggestions and feedback regarding the platform and process by contacting the <strong>People Experience Team (pxp-solutions-TR@bs.nttdata.com)</strong>.",
    Help: "Help",
    Filters: "Filters",
    RequestsList: "Requests List",
    RequestDetail: "Request Detail",
    RequestDetailDescription: "From the list of requests below, you can purchase the product/products you want to supply. For products whose purchase type is product, you can purchase the products individually and send them via cargo/shipping. For the products with gift cards, you can meet the request by entering the code of the gift card into the system.",
    Homepage: "Homepage",
    CreateRequest: "Create Request",
    ProvidedRequestsByMe: "Provided Requests By Me",
    ProvidedRequest: "Provided Request",
    TotalRequest: "Total Request",
    WaitingRequest: "Waiting Request",
    Name: "Name",
    EmployeeNo: "Employee No",
    GSM: "GSM",
    Email: "Email",
    ExpectedDeliveryDate: "Expected Delivery Date",
    Adress: "Adress",
    Quantity: "Quantity",
    Price: "Price",
    PriceUnit: "Price Unit",
    MeasureUnit: "Measure Unit",
    PurchaseType: "Purchase Type",
    ProvidingType: "Providing Type",
    DeliveryType: "Delivery Type",
    Url: "URL",
    RequesterUppercase: "REQUESTER",
    ProductUppercase: "PRODUCT",
    SpecialProduct: "Special Product",
    AddProduct: "Add Product",
    PleaseFill: "Please fill.",
    ProductName: "Product Name",
    ProductSector: "Product Sector",
    ProductQuantity: "Product Quantity",
    ProductPrice: "Product Price",
    ProviderCompany: "Provider Company",
    Yes: "Yes",
    No: "No",
    ResponsibleName: "Responsible Name:",
    ResponsibleEmail: "Responsible E-mail",
    PC: "Piece",
    DIRECT: "Direct",
    SHIPMENT: "Shipment",
    GoToDetail: "Go To Detail",
    Search: "Search",
    RequestNo: "Request No",
    RequestTitle: "Request Title",
    Status: "Status",
    ProvidingRatio: "Providing Ratio",
}