export const translationsTr =
{
    HeaderTitle: "Kalbimiz ve Desteklerimiz Deprem Bölgesinde!",
    HeaderDescription: "Ülkemizin yaşadığı büyük doğal afetin ilk anından itibaren, kalplerimiz afetten etkilenen arkadaşlarımız ve yakınları için atıyor.<br><br>one Heart Dayanışma Platformumuz aracılığıyla, depremdem etkilenen çalışma arkadaşlarımız ve yakınlarının yaşamlarını yeniden kurmaları için onlara el uzatabilir, ihtiyaçlarının giderilmesine destek olabilirsiniz.<br><br>Platform ve sürece dair tüm soru, öneri ve geri bildirimlerinizi <strong> Çalışan Deneyimi Ekibi (pxp-solutions-TR@bs.nttdata.com) </strong> ile iletişime geçerek paylaşabilirsiniz.",
    Help: "Yardım",
    Date: "Tarih",
    Filter: "Filtre",
    Filters: "Filtreler",
    RequestsList: "Talep Listesi",
    RequestDetail: "Talep Detayı",
    RequestDetailDescription: "Aşağıdaki ürün listesinden, karşılamak istediğiniz ürün veya ürünleri satın alabilirsiniz. Satın alma türü alışveriş olan ürünlerde bireysel olarak ürünleri satın alarak kargoya verebilirsiniz. Hediye çeki olan ürünlerde ise, hediye çekinin kodunu sisteme girerek talebi karşılayabilirsiniz.",
    Homepage: "Anasayfa",
    CreateRequest: "Talep Oluştur",
    ProvidedRequestsByMe: "Karşıladığım Talepler",
    ProvidedRequest: "Karşılanan Talep",
    TotalRequest: "Toplam Talep",
    WaitingRequest: "Bekleyen Talep",
    Name: "Adı",
    EmployeeNo: "Personel No",
    GSM: "GSM",
    Email: "Email",
    ExpectedDeliveryDate: "Beklenen Teslim Tarihi",
    Adress: "Adres",
    Quantity: "Adedi",
    Price: "Fiyatı",
    PriceUnit: "Fiyat Birimi",
    MeasureUnit: "Ölçü Birimi",
    PurchaseType: "Satın Alma Türü",
    ProvidingType: "Karşılanma Türü",
    DeliveryType: "Teslimat Türü",
    Url: "URL",
    RequesterUppercase: "TALEP EDEN",
    ProductUppercase: "ÜRÜN",
    SpecialProduct: "Özel Ürün",
    AddProduct: "Ürün Ekle",
    PleaseFill: "Lütfen doldurunuz.",
    ProductName: "Ürün Adı",
    ProductSector: "Ürün Sektörü",
    ProductQuantity: "Ürün Miktarı",
    ProductPrice: "Ürün Fiyatı",
    ProviderCompany: "Tedarik Firması",
    Yes: "Evet",
    No: "Hayır",
    ResponsibleName: "Sorumlu Adı:",
    ResponsibleEmail: "Sorumlu E-mail:",
    PC: "Adet",
    DIRECT: "Elden Teslim",
    SHIPMENT: "Kargo",
    GoToDetail: "Detaya Git",
    Search: "Ara",
    RequestNo: "Talep No",
    RequestTitle: "Talep Başlığı",
    Status: "Durum",
    ProvidingRatio: "Karşılanma Oranı",
    COMPLETED: "Tamamlandı",
    PARTIAL: "Kısmi",
    OPEN: "Açık",
    CANCELLED: "İptal Edildi",
    VERIFIED: "Onaylı",
    UnitPrice: "Birim Fiyat",
    HOMEAPPLIANCES: "Ev Aletleri",
    MULTI: "Çoklu",
    SINGLE: "Tekli",
    PRODUCT: "Ürün",
    VOUCHER: "Hediye Çeki",
    Sector: "Sektörü",
    ELECTRONIC: "Elektronik",
    PleaseSelect: "Lütfen seçiniz.",
    Cancel: "İptal",
    Apply: "Uygula",
    ClearFilter: "Filtreyi Temizle",
}