export const translationsTr =
{
    HeaderTitle: "Kalbimiz Deprem Bölgesinde",
    Help: "Yardım",
    Filters: "Filtreler",
    RequestsList: "Talep Listesi",
    Homepage: "Anasayfa",
    CreateRequest: "Talep Oluştur",
    ProvidedRequestsByMe: "Karşıladığım Talepler",
    ProvidedRequest: "Karşılanan Talep",
    TotalRequest: "Toplam Talep",
    WaitingRequest: "Bekleyen Talep",
    Name: "Adı",
    EmployeeNo: "Personel No",
    GSM: "GSM",
    Email: "Email",
    ExpectedDeliveryDate: "Beklenen Teslim Tarihi",
    Adress: "Adres",
    Quantity: "Adedi",
    Price: "Fiyatı",
    PriceUnit: "Fiyat Birimi",
    MeasureUnit: "Ölçü Birimi",
    PurchaseType: "Satın Alma Türü",
    ProvidingType: "Karşılanma Türü",
    DeliveryType: "Teslimat Türü",
    Url: "URL",
    RequesterUppercase: "TALEP EDEN",
    ProductUppercase: "ÜRÜN",
    SpecialProduct: "Özel Ürün",
    AddProduct: "Ürün Ekle",
    PleaseFill: "Lütfen doldurunuz.",
    ProductName: "Ürün İsmi",
    ProductSector: "Ürün Sektörü",
    ProductQuantity: "Ürün Miktarı",
    ProductPrice: "Ürün Fiyatı",
    ProviderCompany: "Tedarik Firması",
    Yes: "Evet",
    No: "Hayır",
    ResponsibleName: "Sorumlu Adı:",
    PC: "Adet",
    DIRECT: "Elden Teslim",
    SHIPMENT: "Kargo",
    GoToDetail: "Detaya Git",
    Search: "Ara",
    RequestNo: "Talep No",
    RequestTitle: "Talep Başlığı",
    Status: "Durum",
    ProvidingRatio: "Karşılanma Oranı",
}